### ISSUE TITLE
Enabling app fails with Nextcloud 19

### ISSUE THREAD

**Issue by aszlig** [nickv-nextcloud/talk_simple_poll#22]
Installing version `1.3.0` fails on Nextcloud 19 with the following exception:

```
An unhandled exception has been thrown:
Error: Class 'Doctrine\DBAL\Types\Types' not found in ...-nextcloud-19.0.9.1/apps/talk_simple_poll/lib/Migration/Version1000Date20190517081121.php:49
Stack trace:
#0 ...-nextcloud-19.0.9.1/lib/private/DB/MigrationService.php(478): OCA\TalkSimplePoll\Migration\Version1000Date20190517081121->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 ...-nextcloud-19.0.9.1/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep('1000Date2019051...', false)
#2 ...-nextcloud-19.0.9.1/lib/private/Installer.php(157): OC\DB\MigrationService->migrate()
#3 ...-nextcloud-19.0.9.1/core/Command/App/Enable.php(122): OC\Installer->installApp('talk_simple_pol...', false)
#4 ...-nextcloud-19.0.9.1/core/Command/App/Enable.php(92): OC\Core\Command\App\Enable->enableApp('talk_simple_pol...', Array, false, Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 ...-nextcloud-19.0.9.1/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 ...-nextcloud-19.0.9.1/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 ...-nextcloud-19.0.9.1/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 ...-nextcloud-19.0.9.1/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 ...-nextcloud-19.0.9.1/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 ...-nextcloud-19.0.9.1/console.php(85): OC\Console\Application->run()
#11 ...-nextcloud-19.0.9.1/occ(11): require_once('/nix/store/70h0...')
#12 {main}Traceback (most recent call last):
```

Full log from the integration test:

https://headcounter.org/hydra/log/cz06ml3vpbv65dn26zmbmfdpd7iqd4yg-vm-test-run-nextcloud-upgrade.drv

**Comment by nickvergessen** [comment]
Oh sorry, 1.2.0 should work on 19. 1.3.0 is only 20+
