### ISSUE TITLE
Command /polls not working in Nextcloud v.20.0.9

### ISSUE THREAD

**Issue by jekru** [nickv-nextcloud/talk_simple_poll#25]
Simple poll for Nextcloud Talk worked perfectly for Nextcloud 18.0.1
I upgraded to Nextcloud 20.0.9 with Simple poll for Nextcloud Talk 1.3.0 and with these versions, the functionality is now broken.

![image](https://user-images.githubusercontent.com/55323459/118258568-521fed80-b4b0-11eb-8a0f-bc54b2e678d4.png)
![image](https://user-images.githubusercontent.com/55323459/118257018-6f53bc80-b4ae-11eb-837b-ecf2ec42a247.png)

**Response from POST https://www.example.tld/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic**
```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":201,
         "message":"OK"
      },
      "data":{
         "id":93,
         "token":"fy4j9qic",
         "actorType":"bots",
         "actorId":"Poll",
         "actorDisplayName":"Poll-bot",
         "timestamp":1620988382,
         "message":"Beim Ausf\u00fchren des Befehls ist ein Fehler aufgetreten. Bitten Sie einen Administrator, die Protokolle zu \u00fcberpr\u00fcfen.",
         "messageParameters":[
            
         ],
         "systemMessage":"",
         "messageType":"command",
         "isReplyable":false,
         "referenceId":"fc466e4858a61d98be426c64844e4207c6fef7d7"
      }
   }
}
```

**/data/nextcloud.log**
```json

{"reqId":"8t8d4hFhCwC23Ee4Fwag","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"richdocuments","method":"POST","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"8t8d4hFhCwC23Ee4Fwag","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"files_sharing","method":"POST","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"8t8d4hFhCwC23Ee4Fwag","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"talk_simple_poll","method":"POST","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"","user":"--","app":"apporder","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"","user":"--","app":"contacts","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":0,"time":"2021-05-14T10:42:57+00:00","remoteAddr":"","user":"--","app":"richdocuments","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":0,"time":"2021-05-14T10:42:58+00:00","remoteAddr":"","user":"--","app":"files_sharing","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":0,"time":"2021-05-14T10:42:58+00:00","remoteAddr":"","user":"--","app":"talk_simple_poll","method":"","url":"--","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"--","version":"20.0.9.1"}
{"reqId":"jLase16roYzf81dqz9K7","level":1,"time":"2021-05-14T10:42:58+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /var/www/nextcloud/occ in global mode","userAgent":"--","version":"20.0.9.1"}
{"reqId":"8t8d4hFhCwC23Ee4Fwag","level":3,"time":"2021-05-14T10:42:58+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"spreed","method":"POST","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic","message":{"Exception":"InvalidArgumentException","Message":"Chat command failed [Code: 1]: php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/ShellExecutor.php","line":57,"function":"wrapExec","class":"OCA\\Talk\\Chat\\Command\\ShellExecutor","type":"->","args":["php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":208,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\ShellExecutor","type":"->","args":["php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'","Do you like polls?\nYes\nNo","fy4j9qic","admin"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Executor.php","line":109,"function":"execShell","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},"Do you like polls?\nYes\nNo"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/Listener.php","line":72,"function":"exec","class":"OCA\\Talk\\Chat\\Command\\Executor","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OC\\Comments\\Comment"},{"id":2,"__class__":"OCA\\Talk\\Model\\Command"},"Do you like polls?\nYes\nNo",{"__class__":"OCA\\Talk\\Participant"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Talk\\Chat\\Command\\{closure}","class":"OCA\\Talk\\Chat\\Command\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Chat/ChatManager.php","line":195,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/ChatController.php","line":195,"function":"sendMessage","class":"OCA\\Talk\\Chat\\ChatManager","type":"->","args":[{"__class__":"OCA\\Talk\\Room"},{"__class__":"OCA\\Talk\\Participant"},"users","admin","/poll Do you like polls?\nYes\nNo",{"date":"2021-05-14 10:42:57.863461","timezone_type":3,"timezone":"UTC","__class__":"DateTime"},null,"92a52a6f49e5bb6c4255babc1cf603e3ac4c800d"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"sendMessage","class":"OCA\\Talk\\Controller\\ChatController","type":"->","args":["/poll Do you like polls?\nYes\nNo","admin","92a52a6f49e5bb6c4255babc1cf603e3ac4c800d",0]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Talk\\Controller\\ChatController"},"sendMessage"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Talk\\Controller\\ChatController","sendMessage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"apiVersion":"v1","token":"fy4j9qic","_route":"ocs.spreed.Chat.sendMessage"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/spreed/api/v1/chat/fy4j9qic"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/spreed/lib/Chat/Command/ShellExecutor.php","Line":71,"CustomMessage":"Chat command failed [Code: 1]: php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"GJMMADiXQQFMXZKCkGNJ","level":3,"time":"2021-05-14T10:42:58+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"PHP","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=94&includeLastKnown=0","message":"PHP Startup: Unable to load dynamic library 'php_ldap.so' (tried: /usr/lib/php/20170718/php_ldap.so (/usr/lib/php/20170718/php_ldap.so: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/php_ldap.so.so (/usr/lib/php/20170718/php_ldap.so.so: cannot open shared object file: No such file or directory)) at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"vGvPuy4vtL02XWVlwGgV","level":0,"time":"2021-05-14T10:42:59+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"apporder","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=95&includeLastKnown=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"vGvPuy4vtL02XWVlwGgV","level":0,"time":"2021-05-14T10:42:59+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"contacts","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=95&includeLastKnown=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"vGvPuy4vtL02XWVlwGgV","level":0,"time":"2021-05-14T10:42:59+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"richdocuments","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=95&includeLastKnown=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"vGvPuy4vtL02XWVlwGgV","level":0,"time":"2021-05-14T10:42:59+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"files_sharing","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=95&includeLastKnown=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
{"reqId":"vGvPuy4vtL02XWVlwGgV","level":0,"time":"2021-05-14T10:42:59+00:00","remoteAddr":"XX.XXX.XXX.XXX","user":"admin","app":"talk_simple_poll","method":"GET","url":"/nextcloud/ocs/v2.php/apps/spreed/api/v1/chat/fy4j9qic?lookIntoFuture=1&lastKnownMessageId=95&includeLastKnown=0","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","version":"20.0.9.1"}
```

**System information**

- Ubuntu 18.04.1
- PHP 7.2.34
- Apache 2.4.29
- MySQL 5.7.34

**Settings -> Talk**

![image](https://user-images.githubusercontent.com/55323459/118258649-711e7f80-b4b0-11eb-93c7-872d83fa3553.png)

**Comment by nickvergessen** [comment]
Can you run the command from the log manually on your server?
```
sudo -u www-data php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'
```

**Comment by jekru** [comment]
> Can you run the command from the log manually on your server?
> 
> ```
> sudo -u www-data php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'
> ```

```json
root@vXXXXXXXXXXXXXXXXXXX:~# sudo -u www-data php /var/www/nextcloud/occ talk:poll 'fy4j9qic' 'admin' 'Do you like polls?\nYes\nNo'
A poll is already running.

asd (0 votes)

/vote 1 - ds
/vote 2 - as

/poll close - Close the voting and show results
An unhandled exception has been thrown:
TypeError: Return value of "OCA\TalkSimplePoll\Command\Poll::execute()" must be of the type int, "null" returned. in /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\TalkSimplePoll\Command\Poll), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#7 {main}root@vXXXXXXXXXXXXXXXXXXX:~#
root@vXXXXXXXXXXXXXXXXXXX:~#
```

**Comment by jekru** [comment]
I found the problem and got a solution. In the Exception Stack trace, you can see that there is a problem in the /apps/mail folder, so I removed [Mail](https://apps.nextcloud.com/apps/mail) from NextCloud and now it works perfectly. The problem with Mail happened because I had installed 7.2.34 and the requirements for Mail are >=7.3.0,<8.1.0. If you don't need Mail, you can just remove it or upgrade PHP to 7.3.

**Comment by nickvergessen** [comment]
Okay thanks for the hint and debugging. It will be an easy fix, i will make a new version on monday

**Comment by nickvergessen** [comment]
New version available in the appstore and at https://github.com/nickv-nextcloud/talk_simple_poll/releases/tag/v1.3.1
